server:
  port: 7000          #当前服务的端口号
     
eureka:
  client:             #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://192.168.3.107:9000/eureka/,http://192.168.3.107:9001/eureka/
  instance: 
    instance-id: cbdsp-config-client-zuul # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  x

zuul: 
  host:
    max-per-route-connections: 500
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ignored-services: "*"   #设置不能使用微服务名称来访问项目
  routes: 
     user:
       service-id: cbdsp-login-register
       path: /user/**
       strip-prefix: false
     office:
       service-id: cbdsp-office
       path: /office/**
       strip-prefix: false
     root:
       service-id: cbdsp-sm
       path: /root/**
       strip-prefix: false
     perm:
       service-id: cbdsp-sm
       path: /perm/**
       strip-prefix: false
     park:
       service-id: CBDSP-landlord
       path: /park/**
       strip-prefix: false
     order:
       service-id: cbdsp-renter
       path: /order/**
       strip-prefix: false
     lease:
       service-id: cbdsp-renter
       path: /lease/**
       strip-prefix: false
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
 
    
info: #监控信息 
  app.name: CBDSharingParkingSystem
  company.name: www.woniuxy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring: 
  profiles: zuul
  application:
   name: cbdsp-config-client-zuul   #当前服务的名字，后面会用到
