server:
  port: 7000          #当前服务的端口号
     
eureka:
  client:             #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://192.168.3.132:9000/eureka/,http://192.168.3.132:9001/eureka/
  instance: 
    instance-id: cbdsp-config-client-zuul # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  x

zuul: 
  host:
    max-per-route-connections: 500
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ignored-services: "*"   #设置不能使用微服务名称来访问项目
  routes: 
     user:
       service-id: cbdsp-login-register
       path: /user/**
       strip-prefix: false
     office:
       service-id: cbdsp-office
       path: /office/**
       strip-prefix: false
     root:
       service-id: cbdsp-sm
       path: /root/**
       strip-prefix: false
     perm:
       service-id: cbdsp-sm
       path: /perm/**
       strip-prefix: false
     park:
       service-id: CBDSP-landlord
       path: /park/**
       strip-prefix: false
     renter:
       service-id: cbdsp-renter
       path: /renter/**
       strip-prefix: false
     complaint:
       service-id: complaint-provider
       path: /complaint/**
       strip-prefix: false
     page:
       service-id: cbdsp-allpage
       path: /page/**
       strip-prefix: false

ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
 
    
info: #监控信息 
  app.name: CBDSharingParkingSystem
  company.name: www.woniuxy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring: 
  profiles: zuul
  application:
   name: cbdsp-config-client-zuul   #当前服务的名字，后面会用到
# redis的配置信息
  redis:
    database: 0         #连接Redis的库
    host: r-uf6pjy4xqsoeq96t72pd.redis.rds.aliyuncs.com     #主机名称
    port: 6379          # 端口号
    password: Email831100          # 连接密码，没有密码可以不写
    lettuce:            # 設置redis連接池
       pool: 
         max-active: 10   # 最大連接數量
         max-wait: -1     # 連接等待時間，如果為-1 默認不等待
         min-idle: 0      # 最小連接數量
  #配置数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://rm-uf647752du6dt3ee89o.mysql.rds.aliyuncs.com:3306/db_cdbp_user              # 数据库名称
    username: root
    password: hlq19961024@
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                     # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.cbdsp.bean              # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件
