server:
    port: 9000

eureka: 
  instance:
    hostname: cbdsp-config-eureka-9000 #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://127.0.0.1:9001/eureka/
 
spring:
  profiles: eureka9000
  application: 
   name: cbdsp-config-eureka-9000   #当前服务的名字，后面会用到
---   

server:
    port: 9001

eureka: 
  instance:
    hostname: cbdsp-config-eureka-9001 #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://127.0.0.1:9000/eureka/
 
spring:
  profiles: eureka9001
  application: 
   name: cbdsp-config-eureka-9001   #当前服务的名字，后面会用到
